name: base-orphans
version: 0.0.0
synopsis: Backwards-compatible orphan instances for base
license: MIT
author:
  - Simon Hengel <sol@typeful.net>
  - João Cristóvão <jmacristovao@gmail.com>
  - Ryan Scott <ryan.gl.scott@gmail.com>
maintainer:
  - Simon Hengel <sol@typeful.net>
  - João Cristóvão <jmacristovao@gmail.com>
  - Ryan Scott <ryan.gl.scott@gmail.com>
copyright:
  - (c) 2012-2015 Simon Hengel
  - (c) 2014 João Cristóvão
  - (c) 2015 Ryan Scott
category: Compatibility
description: >
  @base-orphans@ defines orphan instances that mimic instances available in
  later versions of @base@ to a wider (older) range of compilers.
  @base-orphans@ does not export anything except the orphan instances
  themselves and complements @<http://hackage.haskell.org/package/base-compat
  base-compat>@.

  `base-orphans-0` is an intentional empty release. For an explanation as to
  why is exists, see the
  <https://github.com/haskell-compat/base-orphans/tree/base-orphans-0#readme README>.

extra-source-files:
  - CHANGES.markdown
  - README.markdown

github: haskell-compat/base-orphans
ghc-options: -Wall
dependencies:
library:
  exposed-modules:
tests:
